<?php

namespace AppBundle\Entity;

use FOS\UserBundle\Model\User as BaseUser;
use Doctrine\ORM\Mapping as ORM;

/**
* @ORM\Entity(repositoryClass="AppBundle\Repository\UserRepository")
* @ORM\Table(name="fos_user")
*/
class User extends BaseUser
{

    /**
    * @ORM\Id
    * @ORM\Column(type="integer")
    * @ORM\GeneratedValue(strategy="AUTO")
    */
    protected $id;

    /**
     * @var string
     *
     * @ORM\Column(name="firstname", type="string", length=30, nullable=true)
     */
    private $firstname;

    /**
     * @var string
     *
     * @ORM\Column(name="surname", type="string", length=30, nullable=true)
     */
    private $surname;

    /**
     * @var string
     *
     * @ORM\Column(name="usertype", type="string", length=10, nullable=true)
     */
    private $usertype;


    // wartości: admin, nauczyciel, uczeń

//    /**
//     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\SchoolClass", inversedBy="users")
//     * @ORM\Column(name="class", type="integer", nullable=true)
//     */
//    private $class;



    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Set firstname
     *
     * @param string $firstname
     * @return User
     */
    public function setFirstName($firstname)
    {
        $this->firstname = $firstname;

        return $this;
    }

    /**
     * Get firstname
     *
     * @return string
     */
    public function getFirstName()
    {
        return $this->firstname;
    }

    /**
     * Set surname
     *
     * @param string $surname
     * @return User
     */
    public function setSurName($surname)
    {
        $this->surname = $surname;

        return $this;
    }

    /**
     * Get surname
     *
     * @return string
     */
    public function getSurName()
    {
        return $this->surname;
    }

    /**
     * Set susertype
     *
     * @param string $usertype
     * @return User
     */
    public function setUserType($usertype)
    {
        $this->usertype = $usertype;

        return $this;
    }

    /**
     * Get usertype
     *
     * @return string
     */
    public function getUserType()
    {
        return $this->usertype;
    }

    public function __toString()
    {
        return $this->getFirstName() .' ' .  $this->getSurName(); // TODO: Change the autogenerated stub
    }

//    /**
//     * Set class
//     *
//     * @param string $class
//     * @return User
//     */
//    public function setClass($class)
//    {
//        $this->class = $class;
//
//        return $this;
//    }
//
//    /**
//     * Get class
//     *
//     * @return string
//     */
//    public function getClass()
//    {
//        return $this->class;
//    }



}